language: php
php:
- 8.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer exec strukt
  - php xcli app:make Payroll
  - php xcli app:reload

script: phpunit
