#!/usr/bin/php
<?php

require "bootstrap.php";

try{
	
	if(!class_exists("App\Loader"))
		throw new Exception("App Loader does not exixst!");
	
	$moduleList = App\Loader::getApp()->getModuleList();	
}
catch(\Exception $e){

	$moduleList = null;
}

$configs = array(

	"labelStruktSect"=>true, 
	// "loadNativeCmd"=>false,
	// "appName"=>"Strukt Console",
	"moduleList"=>$moduleList,
	"appDir"=>"app",
	"rootDir"=>__DIR__
);

$console = new Strukt\Console($configs);
// $console = new Strukt\Console();
exit($console->run($_SERVER["argv"]));